name: masanet-cours-laravel
recipe: laravel
config:
  webroot: ./masanet-cours-laravel/public/
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
     - database
  node:
    type: node:14
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node